# Generated by Django 4.0.6 on 2022-07-27 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_address_line_1_order_address_line_2_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 27, 11, 13, 54, 609446, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
