# Generated by Django 4.0.6 on 2022-08-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount_pence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
