# Generated by Django 4.0.6 on 2022-08-01 10:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_slug_alter_manufacturer_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="links",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
